[Issue 39] R-language scripts
Kinnich/rosetta-io pull request #41
Opened 2023-10-02 18:13 UTC by Kinnich

2023-10-04 15:53 UTC, Kinnich commented on r/json_stdout_object.R
I cannot figure out how to get R to serialize an object to pass the test. This script results in:
`{"1":[0],"a":[1],"bc":[2],"def":[3],"ghij":[4]}`
instead of the desired output for the `test_json_object` test: 
`{"": 0, "a": 1, "bc": 2, "def": 3, "ghij": 4}`

2023-10-04 16:55 UTC, Kinnich commented on r/json_stdout_object.R
Solved by using `auto_unbox` flag in `toJSON` which gets rid of the brackets for atomic vectors (length 1)

2023-10-09 20:50 UTC, Kinnich commented on r/streaming_stdin.R
This is based on the answer to this SE question: https://stackoverflow.com/questions/9370609/piping-stdin-to-r/9370949#9370949

Not sure if I need to close the stdin file or if it's ok to leave it open?

2023-10-10 11:46 UTC, nicholaides requested changes
Looking good! Only had a few changes-- once you fix those, go ahead and merge.

2023-10-10 11:46 UTC, nicholaides commented on r/streaming_stdin.R
hmmm, I never thought about that. After a bit of research it looks like theres no need to close stdin for regular scripts/processes

2023-10-10 11:46 UTC, nicholaides commented on r/json_object_with_array_values.R
This one fails for me because it's missing the `library(jsonlite)`

2023-10-10 11:46 UTC, nicholaides commented on r/streaming_stdin.R
> +open(f)
The `open(f)` line is not needed here

2023-10-11 14:50 UTC, Kinnich commented on r/json_object_with_array_values.R
Good catch. Fails for me too but I just didn't notice. Maybe I should add a pre-merge requirement that the tests all pass

2023-10-11 15:03 UTC, merged